-- One-time DDL for the p4p_submissions table.
-- Run this in the Supabase SQL Editor (supabase-js/PostgREST cannot run DDL).
--
-- This table appears to predate the repo's other SQL migrations (dept_heads,
-- sender_physician_match) — it was created directly in the Supabase dashboard,
-- so there was no source-of-truth DDL for it. This file fills that gap so the
-- schema can be reproduced from source. If the live table already exists,
-- this file is idempotent — safe to run without affecting existing data.
--
-- Written by automation/supabase-client.js logSubmission() on every successful
-- P4P submission email. Read by the /verify/-gated status, list, and ranking
-- pages (restricted column set — see scripts/security-rls-auth.sql Block 1).

create table if not exists public.p4p_submissions (
  id              bigint generated by default as identity primary key,
  physician_name  text        not null,
  department      text,
  work_month      text        not null,  -- e.g. "2569_06"
  submitted_at    timestamptz,
  thread_id       text,                   -- Gmail thread id, for traceability
  filename        text,                   -- submitted .xlsx filename
  created_at      timestamptz not null default now()
);

-- Required by logSubmission()'s upsert onConflict: "physician_name,work_month".
-- ON CONFLICT DO NOTHING there means the FIRST submission for a given
-- physician+month wins; later re-processing of the same email is a no-op.
-- Postgres has no "ADD CONSTRAINT IF NOT EXISTS", so guard it manually.
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'p4p_submissions_physician_month_uniq'
  ) then
    alter table public.p4p_submissions
      add constraint p4p_submissions_physician_month_uniq
      unique (physician_name, work_month);
  end if;
end $$;

-- RLS + grants: see scripts/security-rls-auth.sql Block 1 for the current
-- (authenticated + allow-listed, restricted-column) policy. That script must
-- run after this one on a fresh table.
alter table public.p4p_submissions enable row level security;
